/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LangRouteImport } from './routes/$lang'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AreaRouteImport } from './routes/area'
import { Route as LangIndexRouteImport } from './routes/$lang.index'
import { Route as LangAboutRouteImport } from './routes/$lang.about'
import { Route as LangConciergerieMobilityRouteImport } from './routes/$lang.conciergerie-mobility'
import { Route as LangContactRouteImport } from './routes/$lang.contact'
import { Route as LangEquipoRouteImport } from './routes/$lang.equipo'
import { Route as LangHomeStaySafeRouteImport } from './routes/$lang.home-stay-safe'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminAvisosRouteImport } from './routes/admin.avisos'
import { Route as AdminDespesesRouteImport } from './routes/admin.despeses'
import { Route as AdminEmpresaRouteImport } from './routes/admin.empresa'
import { Route as AdminEquipRouteImport } from './routes/admin.equip'
import { Route as AdminFacturacioRouteImport } from './routes/admin.facturacio'
import { Route as AdminMarquetingRouteImport } from './routes/admin.marqueting'
import { Route as AdminSolicitudsRouteImport } from './routes/admin.solicituds'
import { Route as AdminVisitesRouteImport } from './routes/admin.visites'
import { Route as AreaIndexRouteImport } from './routes/area.index'
import { Route as AreaFacturacionRouteImport } from './routes/area.facturacion'
import { Route as AreaInvitadoRouteImport } from './routes/area.invitado'
import { Route as AreaLlegadaRouteImport } from './routes/area.llegada'
import { Route as AreaPersonasRouteImport } from './routes/area.personas'
import { Route as AreaPeticionesRouteImport } from './routes/area.peticiones'
import { Route as AreaPropiedadRouteImport } from './routes/area.propiedad'
import { Route as AreaAccesoRouteImport } from './routes/area_.acceso'
import { Route as AdminClientsIndexRouteImport } from './routes/admin.clients.index'
import { Route as AdminClientsIdRouteImport } from './routes/admin.clients.$id'
import { Route as AdminPropietatsIndexRouteImport } from './routes/admin.propietats.index'
import { Route as AdminPropietatsIdRouteImport } from './routes/admin.propietats.$id'
import { Route as AreaInformesIndexRouteImport } from './routes/area.informes.index'
import { Route as AreaInformesIdRouteImport } from './routes/area.informes.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LangRoute = LangRouteImport.update({
  id: '/$lang',
  path: '/$lang',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AreaRoute = AreaRouteImport.update({
  id: '/area',
  path: '/area',
  getParentRoute: () => rootRouteImport,
} as any)
const LangIndexRoute = LangIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LangRoute,
} as any)
const LangAboutRoute = LangAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => LangRoute,
} as any)
const LangConciergerieMobilityRoute =
  LangConciergerieMobilityRouteImport.update({
    id: '/conciergerie-mobility',
    path: '/conciergerie-mobility',
    getParentRoute: () => LangRoute,
  } as any)
const LangContactRoute = LangContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => LangRoute,
} as any)
const LangEquipoRoute = LangEquipoRouteImport.update({
  id: '/equipo',
  path: '/equipo',
  getParentRoute: () => LangRoute,
} as any)
const LangHomeStaySafeRoute = LangHomeStaySafeRouteImport.update({
  id: '/home-stay-safe',
  path: '/home-stay-safe',
  getParentRoute: () => LangRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAvisosRoute = AdminAvisosRouteImport.update({
  id: '/avisos',
  path: '/avisos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDespesesRoute = AdminDespesesRouteImport.update({
  id: '/despeses',
  path: '/despeses',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEmpresaRoute = AdminEmpresaRouteImport.update({
  id: '/empresa',
  path: '/empresa',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEquipRoute = AdminEquipRouteImport.update({
  id: '/equip',
  path: '/equip',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFacturacioRoute = AdminFacturacioRouteImport.update({
  id: '/facturacio',
  path: '/facturacio',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMarquetingRoute = AdminMarquetingRouteImport.update({
  id: '/marqueting',
  path: '/marqueting',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSolicitudsRoute = AdminSolicitudsRouteImport.update({
  id: '/solicituds',
  path: '/solicituds',
  getParentRoute: () => AdminRoute,
} as any)
const AdminVisitesRoute = AdminVisitesRouteImport.update({
  id: '/visites',
  path: '/visites',
  getParentRoute: () => AdminRoute,
} as any)
const AreaIndexRoute = AreaIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AreaRoute,
} as any)
const AreaFacturacionRoute = AreaFacturacionRouteImport.update({
  id: '/facturacion',
  path: '/facturacion',
  getParentRoute: () => AreaRoute,
} as any)
const AreaInvitadoRoute = AreaInvitadoRouteImport.update({
  id: '/invitado',
  path: '/invitado',
  getParentRoute: () => AreaRoute,
} as any)
const AreaLlegadaRoute = AreaLlegadaRouteImport.update({
  id: '/llegada',
  path: '/llegada',
  getParentRoute: () => AreaRoute,
} as any)
const AreaPersonasRoute = AreaPersonasRouteImport.update({
  id: '/personas',
  path: '/personas',
  getParentRoute: () => AreaRoute,
} as any)
const AreaPeticionesRoute = AreaPeticionesRouteImport.update({
  id: '/peticiones',
  path: '/peticiones',
  getParentRoute: () => AreaRoute,
} as any)
const AreaPropiedadRoute = AreaPropiedadRouteImport.update({
  id: '/propiedad',
  path: '/propiedad',
  getParentRoute: () => AreaRoute,
} as any)
const AreaAccesoRoute = AreaAccesoRouteImport.update({
  id: '/area_/acceso',
  path: '/area/acceso',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminClientsIndexRoute = AdminClientsIndexRouteImport.update({
  id: '/clients/',
  path: '/clients/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminClientsIdRoute = AdminClientsIdRouteImport.update({
  id: '/clients/$id',
  path: '/clients/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPropietatsIndexRoute = AdminPropietatsIndexRouteImport.update({
  id: '/propietats/',
  path: '/propietats/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPropietatsIdRoute = AdminPropietatsIdRouteImport.update({
  id: '/propietats/$id',
  path: '/propietats/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AreaInformesIndexRoute = AreaInformesIndexRouteImport.update({
  id: '/informes/',
  path: '/informes/',
  getParentRoute: () => AreaRoute,
} as any)
const AreaInformesIdRoute = AreaInformesIdRouteImport.update({
  id: '/informes/$id',
  path: '/informes/$id',
  getParentRoute: () => AreaRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$lang': typeof LangRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/area': typeof AreaRouteWithChildren
  '/$lang/about': typeof LangAboutRoute
  '/$lang/conciergerie-mobility': typeof LangConciergerieMobilityRoute
  '/$lang/contact': typeof LangContactRoute
  '/$lang/equipo': typeof LangEquipoRoute
  '/$lang/home-stay-safe': typeof LangHomeStaySafeRoute
  '/admin/avisos': typeof AdminAvisosRoute
  '/admin/despeses': typeof AdminDespesesRoute
  '/admin/empresa': typeof AdminEmpresaRoute
  '/admin/equip': typeof AdminEquipRoute
  '/admin/facturacio': typeof AdminFacturacioRoute
  '/admin/marqueting': typeof AdminMarquetingRoute
  '/admin/solicituds': typeof AdminSolicitudsRoute
  '/admin/visites': typeof AdminVisitesRoute
  '/area/facturacion': typeof AreaFacturacionRoute
  '/area/invitado': typeof AreaInvitadoRoute
  '/area/llegada': typeof AreaLlegadaRoute
  '/area/personas': typeof AreaPersonasRoute
  '/area/peticiones': typeof AreaPeticionesRoute
  '/area/propiedad': typeof AreaPropiedadRoute
  '/area/acceso': typeof AreaAccesoRoute
  '/$lang/': typeof LangIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/area/': typeof AreaIndexRoute
  '/admin/clients/$id': typeof AdminClientsIdRoute
  '/admin/propietats/$id': typeof AdminPropietatsIdRoute
  '/area/informes/$id': typeof AreaInformesIdRoute
  '/admin/clients/': typeof AdminClientsIndexRoute
  '/admin/propietats/': typeof AdminPropietatsIndexRoute
  '/area/informes/': typeof AreaInformesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$lang/about': typeof LangAboutRoute
  '/$lang/conciergerie-mobility': typeof LangConciergerieMobilityRoute
  '/$lang/contact': typeof LangContactRoute
  '/$lang/equipo': typeof LangEquipoRoute
  '/$lang/home-stay-safe': typeof LangHomeStaySafeRoute
  '/admin/avisos': typeof AdminAvisosRoute
  '/admin/despeses': typeof AdminDespesesRoute
  '/admin/empresa': typeof AdminEmpresaRoute
  '/admin/equip': typeof AdminEquipRoute
  '/admin/facturacio': typeof AdminFacturacioRoute
  '/admin/marqueting': typeof AdminMarquetingRoute
  '/admin/solicituds': typeof AdminSolicitudsRoute
  '/admin/visites': typeof AdminVisitesRoute
  '/area/facturacion': typeof AreaFacturacionRoute
  '/area/invitado': typeof AreaInvitadoRoute
  '/area/llegada': typeof AreaLlegadaRoute
  '/area/personas': typeof AreaPersonasRoute
  '/area/peticiones': typeof AreaPeticionesRoute
  '/area/propiedad': typeof AreaPropiedadRoute
  '/area/acceso': typeof AreaAccesoRoute
  '/$lang': typeof LangIndexRoute
  '/admin': typeof AdminIndexRoute
  '/area': typeof AreaIndexRoute
  '/admin/clients/$id': typeof AdminClientsIdRoute
  '/admin/propietats/$id': typeof AdminPropietatsIdRoute
  '/area/informes/$id': typeof AreaInformesIdRoute
  '/admin/clients': typeof AdminClientsIndexRoute
  '/admin/propietats': typeof AdminPropietatsIndexRoute
  '/area/informes': typeof AreaInformesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$lang': typeof LangRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/area': typeof AreaRouteWithChildren
  '/$lang/about': typeof LangAboutRoute
  '/$lang/conciergerie-mobility': typeof LangConciergerieMobilityRoute
  '/$lang/contact': typeof LangContactRoute
  '/$lang/equipo': typeof LangEquipoRoute
  '/$lang/home-stay-safe': typeof LangHomeStaySafeRoute
  '/admin/avisos': typeof AdminAvisosRoute
  '/admin/despeses': typeof AdminDespesesRoute
  '/admin/empresa': typeof AdminEmpresaRoute
  '/admin/equip': typeof AdminEquipRoute
  '/admin/facturacio': typeof AdminFacturacioRoute
  '/admin/marqueting': typeof AdminMarquetingRoute
  '/admin/solicituds': typeof AdminSolicitudsRoute
  '/admin/visites': typeof AdminVisitesRoute
  '/area/facturacion': typeof AreaFacturacionRoute
  '/area/invitado': typeof AreaInvitadoRoute
  '/area/llegada': typeof AreaLlegadaRoute
  '/area/personas': typeof AreaPersonasRoute
  '/area/peticiones': typeof AreaPeticionesRoute
  '/area/propiedad': typeof AreaPropiedadRoute
  '/area_/acceso': typeof AreaAccesoRoute
  '/$lang/': typeof LangIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/area/': typeof AreaIndexRoute
  '/admin/clients/$id': typeof AdminClientsIdRoute
  '/admin/propietats/$id': typeof AdminPropietatsIdRoute
  '/area/informes/$id': typeof AreaInformesIdRoute
  '/admin/clients/': typeof AdminClientsIndexRoute
  '/admin/propietats/': typeof AdminPropietatsIndexRoute
  '/area/informes/': typeof AreaInformesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$lang'
    | '/admin'
    | '/area'
    | '/$lang/about'
    | '/$lang/conciergerie-mobility'
    | '/$lang/contact'
    | '/$lang/equipo'
    | '/$lang/home-stay-safe'
    | '/admin/avisos'
    | '/admin/despeses'
    | '/admin/empresa'
    | '/admin/equip'
    | '/admin/facturacio'
    | '/admin/marqueting'
    | '/admin/solicituds'
    | '/admin/visites'
    | '/area/facturacion'
    | '/area/invitado'
    | '/area/llegada'
    | '/area/personas'
    | '/area/peticiones'
    | '/area/propiedad'
    | '/area/acceso'
    | '/$lang/'
    | '/admin/'
    | '/area/'
    | '/admin/clients/$id'
    | '/admin/propietats/$id'
    | '/area/informes/$id'
    | '/admin/clients/'
    | '/admin/propietats/'
    | '/area/informes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$lang/about'
    | '/$lang/conciergerie-mobility'
    | '/$lang/contact'
    | '/$lang/equipo'
    | '/$lang/home-stay-safe'
    | '/admin/avisos'
    | '/admin/despeses'
    | '/admin/empresa'
    | '/admin/equip'
    | '/admin/facturacio'
    | '/admin/marqueting'
    | '/admin/solicituds'
    | '/admin/visites'
    | '/area/facturacion'
    | '/area/invitado'
    | '/area/llegada'
    | '/area/personas'
    | '/area/peticiones'
    | '/area/propiedad'
    | '/area/acceso'
    | '/$lang'
    | '/admin'
    | '/area'
    | '/admin/clients/$id'
    | '/admin/propietats/$id'
    | '/area/informes/$id'
    | '/admin/clients'
    | '/admin/propietats'
    | '/area/informes'
  id:
    | '__root__'
    | '/'
    | '/$lang'
    | '/admin'
    | '/area'
    | '/$lang/about'
    | '/$lang/conciergerie-mobility'
    | '/$lang/contact'
    | '/$lang/equipo'
    | '/$lang/home-stay-safe'
    | '/admin/avisos'
    | '/admin/despeses'
    | '/admin/empresa'
    | '/admin/equip'
    | '/admin/facturacio'
    | '/admin/marqueting'
    | '/admin/solicituds'
    | '/admin/visites'
    | '/area/facturacion'
    | '/area/invitado'
    | '/area/llegada'
    | '/area/personas'
    | '/area/peticiones'
    | '/area/propiedad'
    | '/area_/acceso'
    | '/$lang/'
    | '/admin/'
    | '/area/'
    | '/admin/clients/$id'
    | '/admin/propietats/$id'
    | '/area/informes/$id'
    | '/admin/clients/'
    | '/admin/propietats/'
    | '/area/informes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LangRoute: typeof LangRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  AreaRoute: typeof AreaRouteWithChildren
  AreaAccesoRoute: typeof AreaAccesoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang': {
      id: '/$lang'
      path: '/$lang'
      fullPath: '/$lang'
      preLoaderRoute: typeof LangRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/area': {
      id: '/area'
      path: '/area'
      fullPath: '/area'
      preLoaderRoute: typeof AreaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/': {
      id: '/$lang/'
      path: '/'
      fullPath: '/$lang/'
      preLoaderRoute: typeof LangIndexRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/about': {
      id: '/$lang/about'
      path: '/about'
      fullPath: '/$lang/about'
      preLoaderRoute: typeof LangAboutRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/conciergerie-mobility': {
      id: '/$lang/conciergerie-mobility'
      path: '/conciergerie-mobility'
      fullPath: '/$lang/conciergerie-mobility'
      preLoaderRoute: typeof LangConciergerieMobilityRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/contact': {
      id: '/$lang/contact'
      path: '/contact'
      fullPath: '/$lang/contact'
      preLoaderRoute: typeof LangContactRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/equipo': {
      id: '/$lang/equipo'
      path: '/equipo'
      fullPath: '/$lang/equipo'
      preLoaderRoute: typeof LangEquipoRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/home-stay-safe': {
      id: '/$lang/home-stay-safe'
      path: '/home-stay-safe'
      fullPath: '/$lang/home-stay-safe'
      preLoaderRoute: typeof LangHomeStaySafeRouteImport
      parentRoute: typeof LangRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/avisos': {
      id: '/admin/avisos'
      path: '/avisos'
      fullPath: '/admin/avisos'
      preLoaderRoute: typeof AdminAvisosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/despeses': {
      id: '/admin/despeses'
      path: '/despeses'
      fullPath: '/admin/despeses'
      preLoaderRoute: typeof AdminDespesesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/empresa': {
      id: '/admin/empresa'
      path: '/empresa'
      fullPath: '/admin/empresa'
      preLoaderRoute: typeof AdminEmpresaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/equip': {
      id: '/admin/equip'
      path: '/equip'
      fullPath: '/admin/equip'
      preLoaderRoute: typeof AdminEquipRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/facturacio': {
      id: '/admin/facturacio'
      path: '/facturacio'
      fullPath: '/admin/facturacio'
      preLoaderRoute: typeof AdminFacturacioRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/marqueting': {
      id: '/admin/marqueting'
      path: '/marqueting'
      fullPath: '/admin/marqueting'
      preLoaderRoute: typeof AdminMarquetingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/solicituds': {
      id: '/admin/solicituds'
      path: '/solicituds'
      fullPath: '/admin/solicituds'
      preLoaderRoute: typeof AdminSolicitudsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/visites': {
      id: '/admin/visites'
      path: '/visites'
      fullPath: '/admin/visites'
      preLoaderRoute: typeof AdminVisitesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/area/': {
      id: '/area/'
      path: '/'
      fullPath: '/area/'
      preLoaderRoute: typeof AreaIndexRouteImport
      parentRoute: typeof AreaRoute
    }
    '/area/facturacion': {
      id: '/area/facturacion'
      path: '/facturacion'
      fullPath: '/area/facturacion'
      preLoaderRoute: typeof AreaFacturacionRouteImport
      parentRoute: typeof AreaRoute
    }
    '/area/invitado': {
      id: '/area/invitado'
      path: '/invitado'
      fullPath: '/area/invitado'
      preLoaderRoute: typeof AreaInvitadoRouteImport
      parentRoute: typeof AreaRoute
    }
    '/area/llegada': {
      id: '/area/llegada'
      path: '/llegada'
      fullPath: '/area/llegada'
      preLoaderRoute: typeof AreaLlegadaRouteImport
      parentRoute: typeof AreaRoute
    }
    '/area/personas': {
      id: '/area/personas'
      path: '/personas'
      fullPath: '/area/personas'
      preLoaderRoute: typeof AreaPersonasRouteImport
      parentRoute: typeof AreaRoute
    }
    '/area/peticiones': {
      id: '/area/peticiones'
      path: '/peticiones'
      fullPath: '/area/peticiones'
      preLoaderRoute: typeof AreaPeticionesRouteImport
      parentRoute: typeof AreaRoute
    }
    '/area/propiedad': {
      id: '/area/propiedad'
      path: '/propiedad'
      fullPath: '/area/propiedad'
      preLoaderRoute: typeof AreaPropiedadRouteImport
      parentRoute: typeof AreaRoute
    }
    '/area_/acceso': {
      id: '/area_/acceso'
      path: '/area/acceso'
      fullPath: '/area/acceso'
      preLoaderRoute: typeof AreaAccesoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/clients/': {
      id: '/admin/clients/'
      path: '/clients'
      fullPath: '/admin/clients/'
      preLoaderRoute: typeof AdminClientsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/clients/$id': {
      id: '/admin/clients/$id'
      path: '/clients/$id'
      fullPath: '/admin/clients/$id'
      preLoaderRoute: typeof AdminClientsIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/propietats/': {
      id: '/admin/propietats/'
      path: '/propietats'
      fullPath: '/admin/propietats/'
      preLoaderRoute: typeof AdminPropietatsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/propietats/$id': {
      id: '/admin/propietats/$id'
      path: '/propietats/$id'
      fullPath: '/admin/propietats/$id'
      preLoaderRoute: typeof AdminPropietatsIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/area/informes/': {
      id: '/area/informes/'
      path: '/informes'
      fullPath: '/area/informes/'
      preLoaderRoute: typeof AreaInformesIndexRouteImport
      parentRoute: typeof AreaRoute
    }
    '/area/informes/$id': {
      id: '/area/informes/$id'
      path: '/informes/$id'
      fullPath: '/area/informes/$id'
      preLoaderRoute: typeof AreaInformesIdRouteImport
      parentRoute: typeof AreaRoute
    }
  }
}

interface LangRouteChildren {
  LangAboutRoute: typeof LangAboutRoute
  LangConciergerieMobilityRoute: typeof LangConciergerieMobilityRoute
  LangContactRoute: typeof LangContactRoute
  LangEquipoRoute: typeof LangEquipoRoute
  LangHomeStaySafeRoute: typeof LangHomeStaySafeRoute
  LangIndexRoute: typeof LangIndexRoute
}

const LangRouteChildren: LangRouteChildren = {
  LangAboutRoute: LangAboutRoute,
  LangConciergerieMobilityRoute: LangConciergerieMobilityRoute,
  LangContactRoute: LangContactRoute,
  LangEquipoRoute: LangEquipoRoute,
  LangHomeStaySafeRoute: LangHomeStaySafeRoute,
  LangIndexRoute: LangIndexRoute,
}

const LangRouteWithChildren = LangRoute._addFileChildren(LangRouteChildren)

interface AdminRouteChildren {
  AdminAvisosRoute: typeof AdminAvisosRoute
  AdminDespesesRoute: typeof AdminDespesesRoute
  AdminEmpresaRoute: typeof AdminEmpresaRoute
  AdminEquipRoute: typeof AdminEquipRoute
  AdminFacturacioRoute: typeof AdminFacturacioRoute
  AdminMarquetingRoute: typeof AdminMarquetingRoute
  AdminSolicitudsRoute: typeof AdminSolicitudsRoute
  AdminVisitesRoute: typeof AdminVisitesRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminClientsIdRoute: typeof AdminClientsIdRoute
  AdminPropietatsIdRoute: typeof AdminPropietatsIdRoute
  AdminClientsIndexRoute: typeof AdminClientsIndexRoute
  AdminPropietatsIndexRoute: typeof AdminPropietatsIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAvisosRoute: AdminAvisosRoute,
  AdminDespesesRoute: AdminDespesesRoute,
  AdminEmpresaRoute: AdminEmpresaRoute,
  AdminEquipRoute: AdminEquipRoute,
  AdminFacturacioRoute: AdminFacturacioRoute,
  AdminMarquetingRoute: AdminMarquetingRoute,
  AdminSolicitudsRoute: AdminSolicitudsRoute,
  AdminVisitesRoute: AdminVisitesRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminClientsIdRoute: AdminClientsIdRoute,
  AdminPropietatsIdRoute: AdminPropietatsIdRoute,
  AdminClientsIndexRoute: AdminClientsIndexRoute,
  AdminPropietatsIndexRoute: AdminPropietatsIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AreaRouteChildren {
  AreaFacturacionRoute: typeof AreaFacturacionRoute
  AreaInvitadoRoute: typeof AreaInvitadoRoute
  AreaLlegadaRoute: typeof AreaLlegadaRoute
  AreaPersonasRoute: typeof AreaPersonasRoute
  AreaPeticionesRoute: typeof AreaPeticionesRoute
  AreaPropiedadRoute: typeof AreaPropiedadRoute
  AreaIndexRoute: typeof AreaIndexRoute
  AreaInformesIdRoute: typeof AreaInformesIdRoute
  AreaInformesIndexRoute: typeof AreaInformesIndexRoute
}

const AreaRouteChildren: AreaRouteChildren = {
  AreaFacturacionRoute: AreaFacturacionRoute,
  AreaInvitadoRoute: AreaInvitadoRoute,
  AreaLlegadaRoute: AreaLlegadaRoute,
  AreaPersonasRoute: AreaPersonasRoute,
  AreaPeticionesRoute: AreaPeticionesRoute,
  AreaPropiedadRoute: AreaPropiedadRoute,
  AreaIndexRoute: AreaIndexRoute,
  AreaInformesIdRoute: AreaInformesIdRoute,
  AreaInformesIndexRoute: AreaInformesIndexRoute,
}

const AreaRouteWithChildren = AreaRoute._addFileChildren(AreaRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LangRoute: LangRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  AreaRoute: AreaRouteWithChildren,
  AreaAccesoRoute: AreaAccesoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
